import os
import logging

# json files in ./env_setup , prefixes we want to ignore
IGNORE_FILE_PREFIX = ('zappa', 'authdata')

DB_NAME = 'wctf'
RECIPIENT_FILE = 'gpg.recipients'
ZAPPA_FN = 'zappa_settings.json'
CONFIG_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_NAME = 'wctf-c2'
LOG_LEVEL = logging.INFO

FIELD_CTFTOKEN = 'ctftoken'
FIELD_LOG_LEVEL = 'log_level'
FIELD_EVENTS = 'events'
FIELD_LAMBDA_BASE_NAME = 'base_name'
FIELD_LAMBDA_BUCKET = 's3bucket'
FIELD_LAMBDA_PROFILE_NAME = 'profile_name'
FIELD_TEAM_ID = 'team_id'
FIELD_LAMBDA_REGION = 'region'
FIELD_LAMBDA_SG = 'sglambda'
FIELD_LAMBDA_SUB1 = 'privsub1'
FIELD_LAMBDA_SUB2 = 'privsub2'
FIELD_PRIVSUB1 = 'igwsub1'
FIELD_PRIVSUB2 = 'igwsub2'
FIELD_RDS_SG_EXTERNAL = 'sgrdsexternal'
FIELD_RDS_SG_INTERNAL = 'sgrdsinternal'
FIELD_SQL_INSTANCE_TYPE = 'dbinstance'
FIELD_SQL_MASTER_PASS = 'master_password'
FIELD_SQL_MASTER_USER = 'master_user'
FIELD_VPC = 'vpc'
FIELD_SQL_ENDPOINT = 'endpoint_address'
FIELD_SQL_PORT = 'dbport'
FIELD_SQL_USER = 'sql_user'
FIELD_SQL_PASS = 'sql_password'
FIELD_SLACK_VERIFICATION_TOKEN = 'slack_verification_token'
FIELD_SLACK_SIGNING_SECRET = 'slack_signing_secret'
FIELD_SLACK_CLIENT_ID = 'slack_client_id'
FIELD_SLACK_CLIENT_SECRET = 'slack_client_secret'
FIELD_CONNECTION_TYPE = 'connection_type'
FIELD_EXCEPTION_HOOK_URL = 'exception_hook_url'


ENV_EXCEPTION_HOOK_URL = 'EXCEPTION_HOOK_URL'
ENV_SQL_ENDPOINT = 'SQL_ENDPOINT'
ENV_SQL_PORT = 'SQL_PORT'
ENV_SQL_PASS = 'SQL_PASS'
ENV_SQL_USER = 'SQL_USER'
ENV_SQL_MASTER_USER = 'MASTER_SQL_USER'
ENV_SQL_MASTER_PASS = 'MASTER_SQL_PASS'
ENV_SLACK_VERIFICATION_TOKEN = 'SLACK_VERIFICATION_TOKEN'
ENV_SLACK_SIGNING_SECRET = 'SLACK_SIGNING_SECRET'
ENV_SLACK_CLIENT_ID = 'SLACK_CLIENT_ID'
ENV_SLACK_CLIENT_SECRET = 'SLACK_CLIENT_SECRET'
ENV_CONNECTION_TYPE = 'CONNECTION_TYPE'
ENV_CTFTOKEN = 'CTFTOKEN'
ENV_TEAM_ID = 'TEAM_ID'

ENV_MAP = {
    ENV_SQL_ENDPOINT: FIELD_SQL_ENDPOINT,
    ENV_SQL_USER: FIELD_SQL_USER,
    ENV_SQL_PASS: FIELD_SQL_PASS,
    ENV_SQL_PORT: FIELD_SQL_PORT,
    ENV_SLACK_CLIENT_ID: FIELD_SLACK_CLIENT_ID,
    ENV_SLACK_SIGNING_SECRET: FIELD_SLACK_SIGNING_SECRET,
    ENV_SLACK_VERIFICATION_TOKEN: FIELD_SLACK_VERIFICATION_TOKEN,
    ENV_SLACK_CLIENT_SECRET: FIELD_SLACK_CLIENT_SECRET,
    ENV_SLACK_CLIENT_SECRET: FIELD_SLACK_CLIENT_SECRET,
    ENV_SQL_MASTER_USER: FIELD_SQL_MASTER_USER,
    ENV_SQL_MASTER_PASS: FIELD_SQL_MASTER_PASS,
    ENV_CONNECTION_TYPE: FIELD_CONNECTION_TYPE,
    ENV_EXCEPTION_HOOK_URL: FIELD_EXCEPTION_HOOK_URL,
    ENV_CTFTOKEN: FIELD_CTFTOKEN,
    ENV_TEAM_ID: FIELD_TEAM_ID,
}
